#!/bin/bash

set -ex

# Install datasets binary
curl -o datasets 'https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets'
chmod +x datasets


jupyter lab clean

# Setup a workspace
jupyter lab workspaces import binder/workspace.json
