#!/bin/bash

set -ex

# Install datasets binary
curl -o datasets 'https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets'
sudo chmod +x datasets
sudo cp -r ./datasets* /usr/local/bin

